<?php
/**
 * @file
 * Code for the Open Berkeley Pages feature.
 */

include_once('openberkeley_pages.features.inc');

/**
 * Implements hook_modules_enabled().
 *
 * This hook is implemented to assign some default permissions for Panelizer's
 * handling of taxonomy terms. This has to be done in this hook to run after
 * both features and defaultconfig which power the functionality. Hopefully a
 * more general solution can be found.
 * @see http://drupal.org/node/1837312
 */
function openberkeley_pages_modules_enabled($modules) {
  // Only run this logic if we are executing as part of an install profile
  // And only for this particular module.
  if (drupal_installation_attempted() && in_array('openberkeley_pages', $modules)) {

    // Rebuild some caches so this all works right.
    features_revert_module('openberkeley_pages');
    drupal_static_reset('panelizer_entity_plugin_get_handler');

    // Define some permissions for the editor role.
    $editor = user_role_load_by_name('editor');
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page breadcrumbs'));
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page content'));
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page context'));
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page defaults'));
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page layout'));
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page overview'));
    user_role_grant_permissions($editor->rid, array('administer panelizer node openberkeley_content_page settings'));

    // Define some permissions for the administrator role.
    $administrator = user_role_load_by_name('administrator');
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page breadcrumbs'));
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page content'));
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page context'));
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page defaults'));
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page layout'));
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page overview'));
    user_role_grant_permissions($administrator->rid, array('administer panelizer node openberkeley_content_page settings'));
  }
}
